/* This is AUTOGENERATED file. Do NOT edit it. */

#include "constants.h"

/* Decl. of variable for 1st keyword found in <cast.2218.txt.voc> file */
extern char _tid_ [MAX_STR_SIZE];

/* Decl. of variable for 2nd keyword found in <cast.2218.txt.voc> file */
extern char ip_address [MAX_STR_SIZE];

/* Decl. of variable for 3rd keyword found in <cast.2218.txt.voc> file */
extern char ip_mask [MAX_STR_SIZE];

/* Decl. of variable for 4th keyword found in <cast.2218.txt.voc> file */
extern char txt_comname [MAX_STR_SIZE];

/* Decl. of variable for 5th keyword found in <cast.2218.txt.voc> file */
extern char aclId [MAX_STR_SIZE];

/* Decl. of variable for 6th keyword found in <cast.2218.txt.voc> file */
extern char t_mode [MAX_STR_SIZE];

/* Decl. of variable for 7th keyword found in <cast.2218.txt.voc> file */
extern char t_key [MAX_STR_SIZE];

/* Decl. of variable for 8th keyword found in <cast.2218.txt.voc> file */
extern char t_stat [MAX_STR_SIZE];

/* Decl. of variable for 9th keyword found in <cast.2218.txt.voc> file */
extern char chk_ [MAX_STR_SIZE];

/* Decl. of variable for 10th keyword found in <cast.2218.txt.voc> file */
extern char cb_ [MAX_STR_SIZE];

/* Decl. of variable for 11th keyword found in <cast.2218.txt.voc> file */
extern char list_ [MAX_STR_SIZE];

/* Decl. of variable for 12th keyword found in <cast.2218.txt.voc> file */
extern char member_ [MAX_STR_SIZE];

/* Decl. of variable for 13th keyword found in <cast.2218.txt.voc> file */
extern char proof [MAX_STR_SIZE];

/* Decl. of variable for 14th keyword found in <cast.2218.txt.voc> file */
extern char idle [MAX_STR_SIZE];

/* End of AUTOGENERATed file */