/* This is AUTOGENERATED file. Do NOT edit it. */

#include "constants.h"

#include "auxiliary.h"

/* variable for 1st keyword found in <cast.2218.txt.voc> file */
char _tid_ [MAX_STR_SIZE];

/* variable for 2nd keyword found in <cast.2218.txt.voc> file */
char ip_address [MAX_STR_SIZE];

/* variable for 3rd keyword found in <cast.2218.txt.voc> file */
char ip_mask [MAX_STR_SIZE];

/* variable for 4th keyword found in <cast.2218.txt.voc> file */
char txt_comname [MAX_STR_SIZE];

/* variable for 5th keyword found in <cast.2218.txt.voc> file */
char aclId [MAX_STR_SIZE];

/* variable for 6th keyword found in <cast.2218.txt.voc> file */
char t_mode [MAX_STR_SIZE];

/* variable for 7th keyword found in <cast.2218.txt.voc> file */
char t_key [MAX_STR_SIZE];

/* variable for 8th keyword found in <cast.2218.txt.voc> file */
char t_stat [MAX_STR_SIZE];

/* variable for 9th keyword found in <cast.2218.txt.voc> file */
char chk_ [MAX_STR_SIZE];

/* variable for 10th keyword found in <cast.2218.txt.voc> file */
char cb_ [MAX_STR_SIZE];

/* variable for 11th keyword found in <cast.2218.txt.voc> file */
char list_ [MAX_STR_SIZE];

/* variable for 12th keyword found in <cast.2218.txt.voc> file */
char member_ [MAX_STR_SIZE];

/* variable for 13th keyword found in <cast.2218.txt.voc> file */
char proof [MAX_STR_SIZE];

/* variable for 14th keyword found in <cast.2218.txt.voc> file */
char idle [MAX_STR_SIZE];

/* This array provides correspondency between name of variable name and its address */ 
struct _QuineType QuineArray[] =
{
	{ &_tid_   , "_tid_" },

	{ &ip_address   , "ip_address" },

	{ &ip_mask   , "ip_mask" },

	{ &txt_comname   , "txt_comname" },

	{ &aclId   , "aclId" },

	{ &t_mode   , "t_mode" },

	{ &t_key   , "t_key" },

	{ &t_stat   , "t_stat" },

	{ &chk_   , "chk_" },

	{ &cb_   , "cb_" },

	{ &list_   , "list_" },

	{ &member_   , "member_" },

	{ &proof   , "proof" },

	{ &idle   , "idle" },

	/* End of array */
	{0, 0}
};
/* End of AUTOGENERATed file */